name = "files_api"
main = "src/index.ts"
compatibility_date = "2023-11-21"

[vars]
PINATA_ENDPOINT = "https://api.pinata.cloud"
IPFS_GATEWAY_ENDPOINT = "https://cf-ipfs.com"

[[r2_buckets]]
binding = "files"
bucket_name = "files"
